version: '3.7'
services:
  opensearch:
    image: opensearchproject/opensearch:1.3.0
    environment:
      discovery.type: single-node
      plugins.security.disabled:true # disable https and logins
      compatibility.overide_main_response_version: true

    ports:
      - 9200:9200
      - 9600:9600 #required for performance analyzer

    #console at http:localhost:5601/app/dev_tools#/console
  opensearch-dashboards:
      image: opensearchproject/opensearch-dashboards:1.3.0
      ports:
        - 5601:5601
      environment:
        OPENSEARH_HOST : '["http://opensearch:9200"]'
        DISABLE.SECURITY_DASHBOARDS_PLUGIN:  "true"
